apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-enterprise-control-plane
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/example/linkerd-enterprise-control-plane"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: linkerd-buoyant