apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-buoyant
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/example/linkerd-buoyant"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system